"""
Modular LLM Service for AgentLab AI.
Communicates with Groq, OpenAI, or compatible endpoints using native tool calling.
Includes a deterministic fallback mock engine for isolated testing.
"""

import json
from typing import Any, Dict, List, Optional
from openai import OpenAI
from backend.config import settings


class ToolCallItem:
    """Represents a standardized tool call generated by the model."""

    def __init__(self, id: str, name: str, arguments: Dict[str, Any], raw_arguments: str = ""):
        self.id = id
        self.name = name
        self.arguments = arguments
        self.raw_arguments = raw_arguments

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "type": "function",
            "function": {
                "name": self.name,
                "arguments": json.dumps(self.arguments) if self.arguments else self.raw_arguments,
            },
        }


class LLMResult:
    """Standardized response from LLM."""

    def __init__(
        self,
        content: Optional[str] = None,
        tool_calls: Optional[List[ToolCallItem]] = None,
        raw_message: Optional[Any] = None,
    ):
        self.content = content or ""
        self.tool_calls = tool_calls or []
        self.raw_message = raw_message

    @property
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0


class LLMService:
    """Service to interface with LLM providers with native function/tool calling."""

    def __init__(self) -> None:
        self.provider = settings.get_active_provider()
        self.client: Optional[OpenAI] = None

        if self.provider == "groq":
            self.client = OpenAI(
                base_url="https://api.groq.com/openai/v1",
                api_key=settings.GROQ_API_KEY,
            )
        elif self.provider == "openai":
            kwargs: Dict[str, Any] = {"api_key": settings.OPENAI_API_KEY}
            if settings.OPENAI_BASE_URL:
                kwargs["base_url"] = settings.OPENAI_BASE_URL
            self.client = OpenAI(**kwargs)

    def call_llm(
        self,
        messages: List[Dict[str, Any]],
        tools: Optional[List[Dict[str, Any]]] = None,
        model: Optional[str] = None,
        temperature: float = 0.2,
    ) -> LLMResult:
        """
        Send messages and available tools to the LLM.
        Returns parsed text content and/or tool call requests.
        """
        target_model = model or settings.DEFAULT_MODEL

        # If no client or mock provider
        if not self.client or self.provider == "mock":
            return self._mock_call_llm(messages, tools)

        kwargs: Dict[str, Any] = {
            "model": target_model,
            "messages": messages,
            "temperature": temperature,
        }

        # Only pass tools parameter if tools are present
        if tools and len(tools) > 0:
            kwargs["tools"] = tools
            kwargs["tool_choice"] = "auto"

        try:
            response = self.client.chat.completions.create(**kwargs)
            choice = response.choices[0]
            message = choice.message

            tool_calls: List[ToolCallItem] = []
            if message.tool_calls:
                for tc in message.tool_calls:
                    fn_name = tc.function.name
                    raw_args = tc.function.arguments or "{}"
                    try:
                        args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args
                    except json.JSONDecodeError:
                        args = {"raw_input": raw_args}

                    tool_calls.append(
                        ToolCallItem(
                            id=tc.id,
                            name=fn_name,
                            arguments=args,
                            raw_arguments=raw_args,
                        )
                    )

            return LLMResult(
                content=message.content or "",
                tool_calls=tool_calls,
                raw_message=message,
            )
        except Exception as e:
            # Propagate error so loop can handle or report gracefully
            raise RuntimeError(f"LLM API call failed: {str(e)}")

    def _mock_call_llm(
        self, messages: List[Dict[str, Any]], tools: Optional[List[Dict[str, Any]]] = None
    ) -> LLMResult:
        """Deterministic mock response for automated testing when offline."""
        # Find latest user or tool message
        last_msg = messages[-1] if messages else {"role": "user", "content": ""}

        # If previous message was a tool result, produce final answer
        if last_msg.get("role") == "tool":
            content_str = last_msg.get("content", "")
            return LLMResult(
                content=f"Based on the tool execution: {content_str}, here is the verified answer.",
                tool_calls=[],
            )

        # User message routing simulation for tests
        user_text = last_msg.get("content", "").lower()

        # Check if calculator is available in tools
        has_calc = any(t.get("function", {}).get("name") == "calculator" for t in (tools or []))
        if has_calc and any(op in user_text for op in ["calculate", "+", "*", "-", "/", "×"]):
            import re
            m = re.search(r"(\d+[\s\+\-\*\/\%×\(\)]+\d+)", user_text)
            expr = m.group(1).replace("×", "*") if m else "45 * 72"
            return LLMResult(
                content="",
                tool_calls=[ToolCallItem(id="mock_tc_calc", name="calculator", arguments={"expression": expr})],
            )

        has_db = any(t.get("function", {}).get("name") == "database" for t in (tools or []))
        if has_db and ("product" in user_text or "database" in user_text or "table" in user_text):
            return LLMResult(
                content="",
                tool_calls=[ToolCallItem(id="mock_tc_db", name="database", arguments={"operation": "count_products"})],
            )

        has_weather = any(t.get("function", {}).get("name") == "weather" for t in (tools or []))
        if has_weather and "weather" in user_text:
            loc = "Hyderabad" if "hyderabad" in user_text else "London"
            return LLMResult(
                content="",
                tool_calls=[ToolCallItem(id="mock_tc_weather", name="weather", arguments={"location": loc})],
            )

        # Default direct answer
        return LLMResult(
            content="This is a direct answer without tool calling: Machine learning is a field of artificial intelligence.",
            tool_calls=[],
        )


llm_service = LLMService()
